// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace narozip2epub
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class OpfTemplate : OpfTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<?xml version=""1.0"" encoding=""UTF-8""?>
<package
    xmlns=""http://www.idpf.org/2007/opf""
    version=""3.0""
    xml:lang=""ja""
    unique-identifier=""unique-id""
    prefix=""ebpaj: http://www.ebpaj.jp/""
>
<metadata xmlns:dc=""http://purl.org/dc/elements/1.1/"">
<dc:title id=""title"">");
            
            #line 16 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(XmlEncode(_vol.Title)));
            
            #line default
            #line hidden
            this.Write("</dc:title>\r\n<meta refines=\"#title\" property=\"file-as\">");
            
            #line 17 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(XmlEncode(_vol.KanaTitle)));
            
            #line default
            #line hidden
            this.Write("</meta>\r\n\r\n<dc:creator id=\"creator01\">");
            
            #line 19 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(XmlEncode(_vol.Author)));
            
            #line default
            #line hidden
            this.Write("</dc:creator>\r\n<meta refines=\"#creator01\" property=\"role\" scheme=\"marc:relators\">" +
                    "aut</meta>\r\n<meta refines=\"#creator01\" property=\"file-as\">");
            
            #line 21 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(XmlEncode(_vol.KanaAuthor)));
            
            #line default
            #line hidden
            this.Write("</meta>\r\n<meta refines=\"#creator01\" property=\"display-seq\">1</meta>\r\n    \r\n<dc:la" +
                    "nguage>ja</dc:language>\r\n<dc:identifier id=\"unique-id\">urn:uuid:");
            
            #line 25 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_vol.UniqueId));
            
            #line default
            #line hidden
            this.Write("</dc:identifier>\r\n<meta property=\"dcterms:modified\">");
            
            #line 26 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modDate));
            
            #line default
            #line hidden
            this.Write(@"</meta>
<meta property=""ebpaj:guide-version"">1.1.3</meta>
</metadata>

<manifest>
<!-- navigation -->
<item media-type=""application/xhtml+xml"" id=""toc"" href=""navigation-documents.xhtml"" properties=""nav""/>

<!-- style -->
<item media-type=""text/css"" id=""book-style"" href=""style/style.css""/>

<!-- image -->
<item media-type=""image/jpeg"" id=""cover"" href=""image/cover.jpg"" properties=""cover-image""/>

<!-- xhtml -->
<item media-type=""application/xhtml+xml"" id=""p-cover"" href=""xhtml/p-cover.xhtml""/>
<item media-type=""application/xhtml+xml"" id=""p-toc"" href=""xhtml/p-toc.xhtml""/>
");
            
            #line 43 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
 foreach (var sectGrp in _vol.SectionGroups) { 
            
            #line default
            #line hidden
            this.Write("<item media-type=\"application/xhtml+xml\" id=\"");
            
            #line 44 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sectGrp.SectionGroupId));
            
            #line default
            #line hidden
            this.Write("\" href=\"xhtml/");
            
            #line 44 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sectGrp.SectionGroupId));
            
            #line default
            #line hidden
            this.Write(".xhtml\"/>\r\n");
            
            #line 45 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</manifest>\r\n\r\n<spine page-progression-direction=\"rtl\">\r\n<itemref linear=\"yes\" id" +
                    "ref=\"p-cover\"/>\r\n<itemref linear=\"yes\" idref=\"p-toc\"/>\r\n");
            
            #line 51 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
 foreach (var sectGrp in _vol.SectionGroups) { 
            
            #line default
            #line hidden
            this.Write("<itemref linear=\"yes\" idref=\"");
            
            #line 52 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sectGrp.SectionGroupId));
            
            #line default
            #line hidden
            this.Write("\"/>\r\n");
            
            #line 53 "D:\MyPrograms\narozip2epub\narozip2mobi\OpfTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</spine>\r\n\r\n</package>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class OpfTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
